### ISSUE TITLE
テストの記述

### ISSUE THREAD

**Issue by neila** [yk-saito/ic-static-website#1]
- テストはないにせよ、何かしらのスクリプトを呼び出し合否判定をするようにする
  - 案
    - lint check
    - format check
    - svelte use check
    - etc

必要に応じて学習コンテンツに反映する

**Comment by uukait** [comment]
Svelte use checkとして、`npm ls | grep "svelte"` をcodebuild上で実行することとしました。
codebuild上で動作確認OKです！

- [build run log](https://ap-northeast-1.console.aws.amazon.com/codesuite/codebuild/733910873054/projects/stg-codetest/build/stg-codetest%3A6bdb5881-1e92-4af1-b249-099db6c1e56e/?region=ap-northeast-1)

**Comment by neila** [comment]
確認しました！OKです！
